export const translations = {
    en: {
        subtitle: "Resize • Convert • Optimize",
        dropText: "Drop image or",
        browse: "browse",
        remove: "REMOVE",
        dimensions: "Dimensions",
        width: "WIDTH",
        height: "HEIGHT",
        fineTune: "Fine Tune",
        reset: "Reset",
        brightness: "Brightness",
        contrast: "Contrast",
        saturation: "Saturation",
        exportFormat: "Export Format",
        avifNote: "AVIF รองรับเฉพาะ Chrome/Edge เวอร์ชันใหม่",
        download: "DOWNLOAD IMAGE",
        footer: "Privacy First • Local Processing",
        privacyNotice: "TODO: 100% Client-side only. No images are ever sent to or stored on a server.",
    },
    th: {
        subtitle: "ปรับขนาด • แปลงไฟล์ • ปรับแต่ง",
        dropText: "วางรูปภาพที่นี่ หรือ",
        browse: "เลือกไฟล์",
        remove: "ลบรูปออก",
        dimensions: "ขนาดรูปภาพ",
        width: "ความกว้าง",
        height: "ความสูง",
        fineTune: "ปรับแต่งสี",
        reset: "รีเซ็ต",
        brightness: "ความสว่าง",
        contrast: "ความคมชัด",
        saturation: "ความอิ่มสี",
        exportFormat: "รูปแบบไฟล์ที่จะบันทึก",
        avifNote: "AVIF requires Chrome/Edge 121+",
        download: "ดาวน์โหลดรูปภาพ",
        footer: "ปลอดภัยสูงสุด • ประมวลผลในเครื่องคุณเท่านั้น",
        privacyNotice: "หมายเหตุ: ประมวลผลในเครื่อง 100% ไม่มีการอัปโหลดรูปภาพไปเก็บไว้บนเซิร์ฟเวอร์",
    }
};